version: '3'

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    volumes:
      - ./data:/data
      - ./db:/db
      - ./output:/output
      - ./config:/config
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - DB_PATH=/db
      - DATA_DIR=/data
      - OUTPUT_DIR=/output
      - CONFIG_PATH=/config/pipeline_config.json
      - SPACY_MODEL=en_core_web_md

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./db:/db
      - ./config:/config
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - DB_PATH=/db
      - CONFIG_PATH=/config/server_config.json
      - TRANSPORT=stdio
      - SPACY_MODEL=en_core_web_md