services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    volumes:
      - ./data:/data
      - ./output:/output
      - ./db:/db
      - ./config:/config
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_DIR=${DATA_DIR:-/data}
      - OUTPUT_DIR=${OUTPUT_DIR:-/output}
      - DB_PATH=${DB_PATH:-/db}
      - CONFIG_PATH=${CONFIG_PATH:-/config/pipeline_config.json}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - BATCH_SIZE=${BATCH_SIZE:-10}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - SUPPORTED_EXTENSIONS=${SUPPORTED_EXTENSIONS:-.md,.txt}
      - CUSTOM_EMBEDDING_MODULE=${CUSTOM_EMBEDDING_MODULE:-}
      - CUSTOM_EMBEDDING_FUNCTION=${CUSTOM_EMBEDDING_FUNCTION:-}
    restart: "no"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    stdin_open: true
    volumes:
      - ./db:/db
      - ./config:/config
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DB_PATH=${DB_PATH:-/db}
      - CONFIG_PATH=${CONFIG_PATH:-/config/server_config.json}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-7-sonnet-20240307}
      - MAX_RESULTS=${MAX_RESULTS:-10}
      - USE_ANTHROPIC=${USE_ANTHROPIC:-true}
      - TRANSPORT=${TRANSPORT:-stdio}
      - CUSTOM_EMBEDDING_MODULE=${CUSTOM_EMBEDDING_MODULE:-}
      - CUSTOM_EMBEDDING_FUNCTION=${CUSTOM_EMBEDDING_FUNCTION:-}
    restart: unless-stopped